trainingInput:
  scaleTier: BASIC # BASIC | BASIC_GPU | STANDARD_1 | PREMIUM_1
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: iou_eval
    maxTrials: 4
    maxParallelTrials: 2
    params:
    - parameterName: num-layers
      type: INTEGER
      minValue: 1
      maxValue: 15
    - parameterName: epochs
      type: INTEGER
      minValue: 10
      maxValue: 250
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: lr
      type: DOUBLE
      minValue: 0.0001
      maxValue: 0.1
       